# Generated by Django 4.1.5 on 2023-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_video_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Description'),
        ),
    ]
